export const SYNONYMS = {
    sales: {
        label: "Sales/Turnover (Chiffre d'affaires/Ventes)",
        fr: [
            "Chiffre d'affaires",
            "Chiffre d'affaires (CA)",
            "CA",
            "Ventes",
            "Recettes",
            "Revenus",
            "Produits",
            "Chiffre des ventes",
            "Volume des transactions",
            "Volume des ventes",
            "Facturation",
            "Chiffre d'affaires réalisé",
            "Chiffre d'affaires généré",
            "Ventes brutes",
            "Ventes nettes",
            "Chiffre d'affaires hors taxes",
            "Chiffre d'affaires hors taxes (CA HT)",
            "CA HT",
            "Chiffre d'affaires toutes taxes comprises",
            "Chiffre d'affaires toutes taxes comprises (CA TTC)",
            "CA TTC",
            "Volume d'affaires",
            "Chiffre d'affaires net",
        ],
        en: [
            "Sales",
            "Turnover",
            "Revenue",
            "Income",
            "Revenues",
            "Top line",
            "Gross sales",
            "Gross revenue",
            "Total sales",
            "Sales revenue",
            "Total revenue",
            "Net sales",
            "Total sales value",
            "Revenue from sales",
            "Total annual sales",
            "Top-line revenue",
            "Sales turnover",
        ],
    },
    spending: {
        label: "Total Spending (Total des dépenses/Dépenses totales)",
        fr: [
            "Total des dépenses",
            "Dépenses totales",
            "Dépenses",
            "Charges",
            "Dépenses budgétaires",
            "Montant des dépenses",
            "Dépense totale",
            "Dépenses de fonctionnement",
            "Dépenses d'investissement",
            "Dépenses publiques",
            "Sorties d'argent",
            "Frais",
            "Débours",
            "Débourse",
            "Coûts",
        ],
        en: [
            "Total spending",
            "Total expenses",
            "Total expenditure",
            "Overall expenditure",
            "Overall spending",
            "Total outlay",
            "Overall expenses",
            "Total costs",
            "Total cost",
            "Total charges",
            "Total expense",
            "Entire expenditure",
            "Expenses",
            "Expenditure",
            "Costs",
            "Disbursement",
            "Outlay",
            "Spending",
        ],
    },
    unexpectedLoss: {
        label: "Unexpected Loss (UL) (Perte inattendue/Perte imprévue)",
        fr: [
            "Perte inattendue",
            "Perte inattendue (UL)",
            "Perte imprévue",
            "Pertes inattendues",
            "Dépense imprévue",
            "Dépenses imprévues",
            "Pertes imprévues",
            "Perte non anticipée",
            "Déficit imprévu",
        ],
        en: [
            "Unexpected Loss",
            "Unexpected Loss (UL)",
            "UL",
            "Unexpected credit loss",
            "Unanticipated loss",
            "Loss volatility",
            "Unexpected portion of loss",
            "Loss above expected level",
            "Volatility of losses",
        ],
    },
};
