/**
 * Investment Products Catalogue — LELE PFM
 *
 * Comprehensive global coverage: 80+ products across all continents.
 * Products organized by zone, filtered by countryCode at runtime.
 */

import { InvestmentProduct } from '@/types/investment';

// ─── Country Groups ───

// West Africa UEMOA (XOF)
const UEMOA = ['CI', 'SN', 'ML', 'BF', 'NE', 'TG', 'BJ', 'GW'];
// Central Africa CEMAC (XAF)
const CEMAC = ['CM', 'GA', 'CG', 'TD', 'CF', 'GQ'];
// Eurozone
const EUROZONE = ['FR', 'BE', 'DE', 'IT', 'ES', 'PT', 'NL', 'AT', 'IE', 'FI', 'LU', 'GR'];
// East Africa
const EAST_AFRICA = ['KE', 'TZ', 'UG', 'RW', 'ET'];
// Southern Africa
const SOUTHERN_AFRICA = ['ZA', 'BW', 'NA', 'MZ', 'ZW', 'ZM'];
// West Africa anglophone
const WEST_AFRICA_EN = ['NG', 'GH'];
// Maghreb
const MAGHREB = ['MA', 'TN', 'DZ'];
// Gulf GCC
const GCC = ['AE', 'SA', 'QA', 'KW', 'BH', 'OM'];
// Southeast Asia
const SOUTHEAST_ASIA = ['MY', 'ID', 'TH', 'PH', 'VN', 'SG'];
// South Asia
const SOUTH_ASIA = ['IN', 'PK', 'BD', 'LK', 'NP'];
// Latin America
const LATAM = ['BR', 'MX', 'CO', 'CL', 'PE', 'AR', 'EC', 'UY'];
// Caribbean
const CARIBBEAN = ['HT', 'JM', 'TT', 'DO', 'CU'];
// Nordics
const NORDICS = ['SE', 'NO', 'DK', 'FI', 'IS'];
// Eastern Europe
const EASTERN_EUROPE = ['PL', 'CZ', 'HU', 'RO', 'BG', 'HR', 'RS'];
// Sharia-relevant countries
const SHARIA_COUNTRIES = [...GCC, 'MY', 'ID', 'PK', 'BD', 'NG', ...UEMOA, ...CEMAC, 'MA', 'TN', 'EG', 'TR', 'KE', 'TZ'];

export const INVESTMENT_PRODUCTS: InvestmentProduct[] = [

  // ═══════════════════════════════════════════
  // AFRIQUE DE L'OUEST — UEMOA (XOF)
  // ═══════════════════════════════════════════
  {
    code: 'savings_xof',
    asset: 'savings_account',
    name: 'Livret épargne CFA',
    returnRate: 3.5,
    volatility: 0,
    minAmount: 5000,
    currency: 'XOF',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: [...UEMOA, ...CEMAC],
    description: 'Compte épargne classique en Franc CFA, capital garanti',
  },
  {
    code: 'tresor_uemoa',
    asset: 'government_bonds',
    name: 'Bons du Trésor UEMOA',
    returnRate: 5.5,
    volatility: 2,
    minAmount: 10000,
    currency: 'XOF',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: UEMOA,
    description: 'Obligations souveraines UEMOA, maturité 3-12 mois',
  },
  {
    code: 'brvm_index',
    asset: 'local_stocks',
    name: 'Indice BRVM Composite',
    returnRate: 8,
    volatility: 18,
    minAmount: 50000,
    currency: 'XOF',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: UEMOA,
    description: 'Indice boursier régional BRVM, 46 sociétés cotées',
  },
  {
    code: 'tontine_xof',
    asset: 'tontine',
    name: 'Tontine',
    returnRate: 10,
    volatility: 5,
    minAmount: 5000,
    currency: 'XOF',
    liquidity: 'locked',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: [...UEMOA, ...CEMAC, 'HT', 'GN', 'CD'],
    description: 'Épargne rotative communautaire, rendement élevé',
  },
  {
    code: 'opcvm_xof',
    asset: 'mutual_fund',
    name: 'OPCVM UEMOA',
    returnRate: 6,
    volatility: 8,
    minAmount: 100000,
    currency: 'XOF',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: UEMOA,
    description: 'Fonds communs de placement régionaux',
  },

  // ═══════════════════════════════════════════
  // AFRIQUE CENTRALE — CEMAC (XAF)
  // ═══════════════════════════════════════════
  {
    code: 'dat_xaf',
    asset: 'term_deposit',
    name: 'Dépôt à terme CFA',
    returnRate: 4,
    volatility: 0,
    minAmount: 100000,
    currency: 'XAF',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: CEMAC,
    description: 'Dépôt à terme en FCFA, maturité 3-12 mois',
  },
  {
    code: 'tresor_beac',
    asset: 'government_bonds',
    name: 'Bons du Trésor BEAC',
    returnRate: 5,
    volatility: 2,
    minAmount: 10000,
    currency: 'XAF',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: CEMAC,
    description: 'Obligations souveraines BEAC',
  },

  // ═══════════════════════════════════════════
  // NIGERIA (NGN)
  // ═══════════════════════════════════════════
  {
    code: 'savings_ngn',
    asset: 'savings_account',
    name: 'Savings Account NGN',
    returnRate: 5,
    volatility: 0,
    minAmount: 1000,
    currency: 'NGN',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['NG'],
    description: 'High-yield savings in Naira',
  },
  {
    code: 'tbills_ng',
    asset: 'government_bonds',
    name: 'Nigerian Treasury Bills',
    returnRate: 12,
    volatility: 3,
    minAmount: 50000,
    currency: 'NGN',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-exempt',
    riskLevel: 2,
    availableIn: ['NG'],
    description: 'Nigerian government T-Bills, tax-free returns',
  },
  {
    code: 'nse_index',
    asset: 'local_stocks',
    name: 'NGX All-Share Index',
    returnRate: 15,
    volatility: 25,
    minAmount: 10000,
    currency: 'NGN',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 5,
    availableIn: ['NG'],
    description: 'Nigerian Exchange stock index',
  },

  // ═══════════════════════════════════════════
  // GHANA (GHS)
  // ═══════════════════════════════════════════
  {
    code: 'tbills_gh',
    asset: 'government_bonds',
    name: 'Ghana Treasury Bills',
    returnRate: 25,
    volatility: 5,
    minAmount: 100,
    currency: 'GHS',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-exempt',
    riskLevel: 3,
    availableIn: ['GH'],
    description: 'Ghana government T-Bills, high-yield',
  },
  {
    code: 'gse_index',
    asset: 'local_stocks',
    name: 'GSE Composite Index',
    returnRate: 10,
    volatility: 20,
    minAmount: 500,
    currency: 'GHS',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['GH'],
    description: 'Ghana Stock Exchange composite index',
  },

  // ═══════════════════════════════════════════
  // AFRIQUE DE L'EST (KES, TZS, UGX, RWF, ETB)
  // ═══════════════════════════════════════════
  {
    code: 'tbills_ke',
    asset: 'government_bonds',
    name: 'Kenya T-Bills',
    returnRate: 10,
    volatility: 3,
    minAmount: 3000,
    currency: 'KES',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-exempt',
    riskLevel: 2,
    availableIn: ['KE'],
    description: 'Kenyan government treasury bills',
  },
  {
    code: 'nse_ke',
    asset: 'local_stocks',
    name: 'NSE 20 Index',
    returnRate: 8,
    volatility: 20,
    minAmount: 5000,
    currency: 'KES',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['KE'],
    description: 'Nairobi Securities Exchange index',
  },
  {
    code: 'mmf_ke',
    asset: 'money_market',
    name: 'Money Market Fund KE',
    returnRate: 9,
    volatility: 1,
    minAmount: 1000,
    currency: 'KES',
    liquidity: 'immediate',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['KE'],
    description: 'Kenya money market fund, daily liquidity',
  },
  {
    code: 'tbills_tz',
    asset: 'government_bonds',
    name: 'Tanzania T-Bills',
    returnRate: 8,
    volatility: 3,
    minAmount: 500000,
    currency: 'TZS',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['TZ'],
    description: 'Tanzania government treasury bills',
  },
  {
    code: 'tbills_ug',
    asset: 'government_bonds',
    name: 'Uganda T-Bills',
    returnRate: 10,
    volatility: 3,
    minAmount: 100000,
    currency: 'UGX',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['UG'],
    description: 'Uganda government treasury bills',
  },
  {
    code: 'savings_rw',
    asset: 'savings_account',
    name: 'Rwanda Savings',
    returnRate: 6,
    volatility: 0,
    minAmount: 5000,
    currency: 'RWF',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['RW'],
    description: 'Rwanda high-yield savings account',
  },
  {
    code: 'tbills_et',
    asset: 'government_bonds',
    name: 'Ethiopia T-Bills',
    returnRate: 8,
    volatility: 4,
    minAmount: 5000,
    currency: 'ETB',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['ET'],
    description: 'Ethiopian government treasury bills',
  },

  // ═══════════════════════════════════════════
  // AFRIQUE AUSTRALE (ZAR, BWP, NAD)
  // ═══════════════════════════════════════════
  {
    code: 'tfsa_za',
    asset: 'savings_account',
    name: 'Tax-Free Savings ZA',
    returnRate: 7,
    volatility: 0,
    minAmount: 500,
    currency: 'ZAR',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'TFSA',
    riskLevel: 1,
    availableIn: ['ZA'],
    description: 'Tax-free savings account, R36,000/year limit',
  },
  {
    code: 'jse_top40',
    asset: 'local_stocks',
    name: 'JSE Top 40',
    returnRate: 10,
    volatility: 18,
    minAmount: 1000,
    currency: 'ZAR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['ZA', 'NA', 'BW'],
    description: 'Johannesburg Stock Exchange Top 40 index',
  },
  {
    code: 'mmf_za',
    asset: 'money_market',
    name: 'Money Market Fund ZA',
    returnRate: 7.5,
    volatility: 1,
    minAmount: 500,
    currency: 'ZAR',
    liquidity: 'immediate',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['ZA'],
    description: 'South Africa money market fund',
  },
  {
    code: 'reit_za',
    asset: 'real_estate_fund',
    name: 'SA REIT Index',
    returnRate: 8,
    volatility: 12,
    minAmount: 1000,
    currency: 'ZAR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['ZA'],
    description: 'South Africa listed REITs',
  },

  // ═══════════════════════════════════════════
  // EGYPTE (EGP)
  // ═══════════════════════════════════════════
  {
    code: 'tbills_eg',
    asset: 'government_bonds',
    name: 'Egypt Treasury Bills',
    returnRate: 22,
    volatility: 5,
    minAmount: 25000,
    currency: 'EGP',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['EG'],
    description: 'Egyptian government T-Bills, high yield',
  },
  {
    code: 'egx30',
    asset: 'local_stocks',
    name: 'EGX 30 Index',
    returnRate: 12,
    volatility: 22,
    minAmount: 5000,
    currency: 'EGP',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['EG'],
    description: 'Egyptian Exchange EGX30 index',
  },

  // ═══════════════════════════════════════════
  // MAGHREB (MAD, TND, DZD)
  // ═══════════════════════════════════════════
  {
    code: 'opcvm_mad',
    asset: 'mutual_fund',
    name: 'OPCVM Maroc',
    returnRate: 6,
    volatility: 8,
    minAmount: 500,
    currency: 'MAD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['MA'],
    description: 'Fonds communs de placement marocains',
  },
  {
    code: 'bourse_casa',
    asset: 'local_stocks',
    name: 'Bourse de Casablanca',
    returnRate: 8,
    volatility: 15,
    minAmount: 1000,
    currency: 'MAD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['MA'],
    description: 'Indice MASI de la Bourse de Casablanca',
  },
  {
    code: 'dat_mad',
    asset: 'term_deposit',
    name: 'Dépôt à terme MAD',
    returnRate: 3.5,
    volatility: 0,
    minAmount: 5000,
    currency: 'MAD',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['MA'],
    description: 'Dépôt à terme bancaire au Maroc',
  },
  {
    code: 'bvmt_tn',
    asset: 'local_stocks',
    name: 'BVMT Tunindex',
    returnRate: 7,
    volatility: 14,
    minAmount: 500,
    currency: 'TND',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['TN'],
    description: 'Bourse de Tunis Tunindex',
  },
  {
    code: 'dat_tn',
    asset: 'term_deposit',
    name: 'Dépôt à terme TND',
    returnRate: 7,
    volatility: 0,
    minAmount: 1000,
    currency: 'TND',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['TN'],
    description: 'Dépôt à terme en Tunisie',
  },
  {
    code: 'savings_dz',
    asset: 'savings_account',
    name: 'Livret épargne DZD',
    returnRate: 3,
    volatility: 0,
    minAmount: 5000,
    currency: 'DZD',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['DZ'],
    description: 'Livret épargne algérien',
  },

  // ═══════════════════════════════════════════
  // FRANCE (EUR)
  // ═══════════════════════════════════════════
  {
    code: 'livret_a',
    asset: 'savings_account',
    name: 'Livret A',
    returnRate: 3,
    volatility: 0,
    minAmount: 10,
    currency: 'EUR',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'Livret A',
    riskLevel: 1,
    availableIn: ['FR'],
    description: 'Livret réglementé, exonéré d\'impôts',
  },
  {
    code: 'pea_etf',
    asset: 'stock_index',
    name: 'ETF World via PEA',
    returnRate: 8,
    volatility: 15,
    minAmount: 100,
    currency: 'EUR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'PEA',
    riskLevel: 3,
    availableIn: ['FR'],
    description: 'ETF MSCI World en PEA, fiscalité avantageuse après 5 ans',
  },
  {
    code: 'av_fonds_euro',
    asset: 'money_market',
    name: 'Fonds Euro (Assurance Vie)',
    returnRate: 3,
    volatility: 1,
    minAmount: 100,
    currency: 'EUR',
    liquidity: 'weeks',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Assurance Vie',
    riskLevel: 1,
    availableIn: ['FR'],
    description: 'Fonds euro capital garanti en assurance vie',
  },
  {
    code: 'scpi_fr',
    asset: 'real_estate_fund',
    name: 'SCPI',
    returnRate: 5,
    volatility: 5,
    minAmount: 1000,
    currency: 'EUR',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['FR', 'BE'],
    description: 'Pierre papier, rendement locatif mutualisé',
  },

  // ═══════════════════════════════════════════
  // EUROPE — Zone Euro (EUR)
  // ═══════════════════════════════════════════
  {
    code: 'etf_world_eur',
    asset: 'stock_index',
    name: 'ETF MSCI World',
    returnRate: 8,
    volatility: 15,
    minAmount: 50,
    currency: 'EUR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: [...EUROZONE, 'CH'],
    description: 'Indice mondial diversifié, 1600+ entreprises',
  },
  {
    code: 'euro_govt_bonds',
    asset: 'government_bonds',
    name: 'Obligations d\'État Eurozone',
    returnRate: 3,
    volatility: 4,
    minAmount: 100,
    currency: 'EUR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: EUROZONE,
    description: 'Obligations souveraines zone euro',
  },

  // ═══════════════════════════════════════════
  // ROYAUME-UNI (GBP)
  // ═══════════════════════════════════════════
  {
    code: 'isa_uk',
    asset: 'savings_account',
    name: 'Cash ISA',
    returnRate: 4,
    volatility: 0,
    minAmount: 1,
    currency: 'GBP',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'ISA',
    riskLevel: 1,
    availableIn: ['GB'],
    description: 'Tax-free cash ISA, £20,000/year allowance',
  },
  {
    code: 'stocks_isa_uk',
    asset: 'stock_index',
    name: 'Stocks & Shares ISA',
    returnRate: 8,
    volatility: 15,
    minAmount: 50,
    currency: 'GBP',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Stocks & Shares ISA',
    riskLevel: 3,
    availableIn: ['GB'],
    description: 'Tax-free investment ISA, global index funds',
  },
  {
    code: 'ftse100',
    asset: 'local_stocks',
    name: 'FTSE 100 ETF',
    returnRate: 7,
    volatility: 14,
    minAmount: 50,
    currency: 'GBP',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['GB'],
    description: 'UK top 100 companies index',
  },
  {
    code: 'sipp_uk',
    asset: 'mutual_fund',
    name: 'SIPP Pension',
    returnRate: 7,
    volatility: 12,
    minAmount: 100,
    currency: 'GBP',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'SIPP',
    riskLevel: 3,
    availableIn: ['GB'],
    description: 'Self-invested personal pension, tax relief on contributions',
  },

  // ═══════════════════════════════════════════
  // SUISSE (CHF)
  // ═══════════════════════════════════════════
  {
    code: 'pillar3a_ch',
    asset: 'mutual_fund',
    name: 'Pilier 3a',
    returnRate: 4,
    volatility: 8,
    minAmount: 100,
    currency: 'CHF',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Pilier 3a',
    riskLevel: 2,
    availableIn: ['CH'],
    description: 'Prévoyance liée, déduction fiscale, CHF 7,056/an',
  },
  {
    code: 'smi_ch',
    asset: 'local_stocks',
    name: 'SMI Index',
    returnRate: 7,
    volatility: 14,
    minAmount: 100,
    currency: 'CHF',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['CH'],
    description: 'Swiss Market Index, top 20 companies',
  },

  // ═══════════════════════════════════════════
  // SCANDINAVIE / NORDIQUES
  // ═══════════════════════════════════════════
  {
    code: 'isk_se',
    asset: 'stock_index',
    name: 'ISK Investment Account',
    returnRate: 8,
    volatility: 15,
    minAmount: 100,
    currency: 'SEK',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'ISK',
    riskLevel: 3,
    availableIn: ['SE'],
    description: 'Swedish ISK account, flat tax on capital',
  },
  {
    code: 'ask_no',
    asset: 'stock_index',
    name: 'ASK Aksjesparekonto',
    returnRate: 8,
    volatility: 15,
    minAmount: 500,
    currency: 'NOK',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'ASK',
    riskLevel: 3,
    availableIn: ['NO'],
    description: 'Norwegian share savings account, tax-deferred',
  },
  {
    code: 'aktiespar_dk',
    asset: 'stock_index',
    name: 'Aktiesparekonto',
    returnRate: 8,
    volatility: 15,
    minAmount: 500,
    currency: 'DKK',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Aktiesparekonto',
    riskLevel: 3,
    availableIn: ['DK'],
    description: 'Danish share savings account, 17% flat tax',
  },

  // ═══════════════════════════════════════════
  // EUROPE DE L'EST
  // ═══════════════════════════════════════════
  {
    code: 'ike_pl',
    asset: 'stock_index',
    name: 'IKE/IKZE (Poland)',
    returnRate: 7,
    volatility: 16,
    minAmount: 200,
    currency: 'PLN',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'IKE/IKZE',
    riskLevel: 3,
    availableIn: ['PL'],
    description: 'Polish tax-advantaged retirement accounts',
  },
  {
    code: 'wig20_pl',
    asset: 'local_stocks',
    name: 'WIG20 Index',
    returnRate: 8,
    volatility: 20,
    minAmount: 100,
    currency: 'PLN',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['PL'],
    description: 'Warsaw Stock Exchange top 20',
  },
  {
    code: 'govt_bonds_cz',
    asset: 'government_bonds',
    name: 'Czech Government Bonds',
    returnRate: 4,
    volatility: 3,
    minAmount: 1000,
    currency: 'CZK',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['CZ'],
    description: 'Czech Republic sovereign bonds',
  },
  {
    code: 'map_hu',
    asset: 'government_bonds',
    name: 'MÁP+ Hungarian Bonds',
    returnRate: 10,
    volatility: 2,
    minAmount: 10000,
    currency: 'HUF',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-exempt',
    riskLevel: 2,
    availableIn: ['HU'],
    description: 'Hungarian premium government bonds',
  },
  {
    code: 'bet_ro',
    asset: 'local_stocks',
    name: 'BET Index Romania',
    returnRate: 10,
    volatility: 18,
    minAmount: 500,
    currency: 'RON',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['RO'],
    description: 'Bucharest Exchange Trading index',
  },

  // ═══════════════════════════════════════════
  // TURQUIE (TRY)
  // ═══════════════════════════════════════════
  {
    code: 'bist100_tr',
    asset: 'local_stocks',
    name: 'BIST 100',
    returnRate: 25,
    volatility: 30,
    minAmount: 500,
    currency: 'TRY',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 5,
    availableIn: ['TR'],
    description: 'Borsa Istanbul top 100 index',
  },
  {
    code: 'govt_bonds_tr',
    asset: 'government_bonds',
    name: 'Devlet Tahvili',
    returnRate: 30,
    volatility: 8,
    minAmount: 1000,
    currency: 'TRY',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['TR'],
    description: 'Turkish government bonds, high yield',
  },
  {
    code: 'participation_tr',
    asset: 'sukuk',
    name: 'Katılım Hesabı',
    returnRate: 20,
    volatility: 3,
    minAmount: 500,
    currency: 'TRY',
    liquidity: 'months',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['TR'],
    description: 'Participation account (Islamic banking Turkey)',
  },

  // ═══════════════════════════════════════════
  // USA (USD)
  // ═══════════════════════════════════════════
  {
    code: 'hysa_usd',
    asset: 'savings_account',
    name: 'High-Yield Savings',
    returnRate: 4.5,
    volatility: 0,
    minAmount: 1,
    currency: 'USD',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['US'],
    description: 'High-yield savings account, FDIC insured',
  },
  {
    code: 'sp500_etf',
    asset: 'stock_index',
    name: 'S&P 500 ETF',
    returnRate: 10,
    volatility: 16,
    minAmount: 1,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['US', 'CA', 'GB'],
    description: 'Broad US market index ETF',
  },
  {
    code: 'treasury_usd',
    asset: 'government_bonds',
    name: 'US Treasury Bonds',
    returnRate: 4,
    volatility: 5,
    minAmount: 100,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['US'],
    description: 'US government bonds, very low risk',
  },
  {
    code: 'roth_ira',
    asset: 'stock_index',
    name: 'Roth IRA',
    returnRate: 9,
    volatility: 14,
    minAmount: 50,
    currency: 'USD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Roth IRA',
    riskLevel: 3,
    availableIn: ['US'],
    description: 'Tax-free growth retirement account, $7,000/year',
  },
  {
    code: 'reit_us',
    asset: 'real_estate_fund',
    name: 'US REIT ETF',
    returnRate: 7,
    volatility: 15,
    minAmount: 50,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['US'],
    description: 'US real estate investment trust index',
  },

  // ═══════════════════════════════════════════
  // CANADA (CAD)
  // ═══════════════════════════════════════════
  {
    code: 'tfsa_ca',
    asset: 'savings_account',
    name: 'TFSA',
    returnRate: 4,
    volatility: 0,
    minAmount: 1,
    currency: 'CAD',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'TFSA',
    riskLevel: 1,
    availableIn: ['CA'],
    description: 'Tax-Free Savings Account, $7,000/year',
  },
  {
    code: 'rrsp_ca',
    asset: 'mutual_fund',
    name: 'RRSP',
    returnRate: 7,
    volatility: 12,
    minAmount: 100,
    currency: 'CAD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'RRSP',
    riskLevel: 3,
    availableIn: ['CA'],
    description: 'Registered Retirement Savings Plan, tax-deferred',
  },
  {
    code: 'tsx_ca',
    asset: 'local_stocks',
    name: 'TSX Composite',
    returnRate: 8,
    volatility: 14,
    minAmount: 50,
    currency: 'CAD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['CA'],
    description: 'Toronto Stock Exchange composite index',
  },

  // ═══════════════════════════════════════════
  // AMÉRIQUE LATINE
  // ═══════════════════════════════════════════
  {
    code: 'tesouro_br',
    asset: 'government_bonds',
    name: 'Tesouro Direto',
    returnRate: 10,
    volatility: 3,
    minAmount: 30,
    currency: 'BRL',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['BR'],
    description: 'Brazilian government bonds, accessible online',
  },
  {
    code: 'ibovespa_br',
    asset: 'local_stocks',
    name: 'Ibovespa ETF',
    returnRate: 12,
    volatility: 22,
    minAmount: 100,
    currency: 'BRL',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['BR'],
    description: 'Brazilian stock market index',
  },
  {
    code: 'poupanca_br',
    asset: 'savings_account',
    name: 'Poupança',
    returnRate: 6,
    volatility: 0,
    minAmount: 1,
    currency: 'BRL',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-exempt',
    riskLevel: 1,
    availableIn: ['BR'],
    description: 'Brazilian regulated savings, tax-free',
  },
  {
    code: 'cetes_mx',
    asset: 'government_bonds',
    name: 'CETES',
    returnRate: 10,
    volatility: 2,
    minAmount: 100,
    currency: 'MXN',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['MX'],
    description: 'Mexican government certificates of deposit',
  },
  {
    code: 'afore_mx',
    asset: 'mutual_fund',
    name: 'AFORE',
    returnRate: 8,
    volatility: 8,
    minAmount: 100,
    currency: 'MXN',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'AFORE',
    riskLevel: 2,
    availableIn: ['MX'],
    description: 'Mexican retirement fund, employer-matched',
  },
  {
    code: 'bmv_mx',
    asset: 'local_stocks',
    name: 'BMV IPC Index',
    returnRate: 9,
    volatility: 18,
    minAmount: 500,
    currency: 'MXN',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['MX'],
    description: 'Mexican Stock Exchange main index',
  },
  {
    code: 'cdt_co',
    asset: 'term_deposit',
    name: 'CDT Colombia',
    returnRate: 9,
    volatility: 0,
    minAmount: 100000,
    currency: 'COP',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['CO'],
    description: 'Colombian term deposit certificate',
  },
  {
    code: 'bvc_co',
    asset: 'local_stocks',
    name: 'COLCAP Index',
    returnRate: 8,
    volatility: 20,
    minAmount: 100000,
    currency: 'COP',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['CO'],
    description: 'Bolsa de Valores de Colombia index',
  },
  {
    code: 'afp_cl',
    asset: 'mutual_fund',
    name: 'AFP Chile',
    returnRate: 6,
    volatility: 10,
    minAmount: 0,
    currency: 'CLP',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'AFP',
    riskLevel: 3,
    availableIn: ['CL'],
    description: 'Chilean pension fund, mandatory + voluntary',
  },
  {
    code: 'ipsa_cl',
    asset: 'local_stocks',
    name: 'IPSA Index',
    returnRate: 7,
    volatility: 16,
    minAmount: 10000,
    currency: 'CLP',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['CL'],
    description: 'Santiago Stock Exchange selective index',
  },
  {
    code: 'afp_pe',
    asset: 'mutual_fund',
    name: 'AFP Perú',
    returnRate: 7,
    volatility: 10,
    minAmount: 0,
    currency: 'PEN',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'AFP',
    riskLevel: 3,
    availableIn: ['PE'],
    description: 'Peruvian pension fund system',
  },
  {
    code: 'plazo_fijo_ar',
    asset: 'term_deposit',
    name: 'Plazo Fijo UVA',
    returnRate: 80,
    volatility: 10,
    minAmount: 10000,
    currency: 'ARS',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['AR'],
    description: 'Argentine inflation-adjusted fixed deposit',
  },

  // ═══════════════════════════════════════════
  // CARAÏBES
  // ═══════════════════════════════════════════
  {
    code: 'savings_jm',
    asset: 'savings_account',
    name: 'Jamaica Savings',
    returnRate: 5,
    volatility: 0,
    minAmount: 1000,
    currency: 'JMD',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['JM'],
    description: 'Jamaican high-yield savings account',
  },
  {
    code: 'tbills_tt',
    asset: 'government_bonds',
    name: 'T&T Government Bonds',
    returnRate: 5,
    volatility: 2,
    minAmount: 1000,
    currency: 'TTD',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['TT'],
    description: 'Trinidad & Tobago government bonds',
  },

  // ═══════════════════════════════════════════
  // MOYEN-ORIENT — GCC
  // ═══════════════════════════════════════════
  {
    code: 'national_bonds_ae',
    asset: 'government_bonds',
    name: 'National Bonds UAE',
    returnRate: 5,
    volatility: 1,
    minAmount: 100,
    currency: 'AED',
    liquidity: 'months',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-free',
    riskLevel: 1,
    availableIn: ['AE'],
    description: 'UAE National Bonds, sharia-compliant',
  },
  {
    code: 'adx_ae',
    asset: 'local_stocks',
    name: 'ADX General Index',
    returnRate: 10,
    volatility: 15,
    minAmount: 1000,
    currency: 'AED',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-free',
    riskLevel: 3,
    availableIn: ['AE'],
    description: 'Abu Dhabi Securities Exchange index',
  },
  {
    code: 'reit_ae',
    asset: 'real_estate_fund',
    name: 'UAE REIT',
    returnRate: 6,
    volatility: 10,
    minAmount: 5000,
    currency: 'AED',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-free',
    riskLevel: 3,
    availableIn: ['AE'],
    description: 'UAE real estate investment trust',
  },
  {
    code: 'tadawul_sa',
    asset: 'local_stocks',
    name: 'Tadawul All Share',
    returnRate: 9,
    volatility: 16,
    minAmount: 1000,
    currency: 'SAR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-free',
    riskLevel: 3,
    availableIn: ['SA'],
    description: 'Saudi Arabian stock exchange index',
  },
  {
    code: 'sama_bills_sa',
    asset: 'government_bonds',
    name: 'SAMA Bills',
    returnRate: 5,
    volatility: 1,
    minAmount: 5000,
    currency: 'SAR',
    liquidity: 'months',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-free',
    riskLevel: 1,
    availableIn: ['SA'],
    description: 'Saudi Central Bank short-term bills',
  },
  {
    code: 'qse_qa',
    asset: 'local_stocks',
    name: 'QSE Index',
    returnRate: 7,
    volatility: 14,
    minAmount: 5000,
    currency: 'QAR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-free',
    riskLevel: 3,
    availableIn: ['QA'],
    description: 'Qatar Stock Exchange index',
  },
  {
    code: 'nbk_kw',
    asset: 'savings_account',
    name: 'Kuwait Savings',
    returnRate: 4,
    volatility: 0,
    minAmount: 100,
    currency: 'KWD',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-free',
    riskLevel: 1,
    availableIn: ['KW'],
    description: 'Kuwait high-yield savings, tax-free',
  },

  // ═══════════════════════════════════════════
  // INDE (INR)
  // ═══════════════════════════════════════════
  {
    code: 'ppf_in',
    asset: 'savings_account',
    name: 'PPF (Public Provident Fund)',
    returnRate: 7.1,
    volatility: 0,
    minAmount: 500,
    currency: 'INR',
    liquidity: 'locked',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'Section 80C',
    riskLevel: 1,
    availableIn: ['IN'],
    description: 'Government-backed savings, 15-year lock-in, EEE tax status',
  },
  {
    code: 'nps_in',
    asset: 'mutual_fund',
    name: 'NPS (National Pension)',
    returnRate: 9,
    volatility: 10,
    minAmount: 500,
    currency: 'INR',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Section 80CCD',
    riskLevel: 2,
    availableIn: ['IN'],
    description: 'National Pension System, extra ₹50,000 tax deduction',
  },
  {
    code: 'nifty50_in',
    asset: 'local_stocks',
    name: 'Nifty 50 ETF',
    returnRate: 12,
    volatility: 16,
    minAmount: 500,
    currency: 'INR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['IN'],
    description: 'NSE Nifty 50 index ETF, top Indian companies',
  },
  {
    code: 'fd_in',
    asset: 'term_deposit',
    name: 'Fixed Deposit India',
    returnRate: 7,
    volatility: 0,
    minAmount: 1000,
    currency: 'INR',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['IN'],
    description: 'Bank fixed deposit, guaranteed returns',
  },

  // ═══════════════════════════════════════════
  // PAKISTAN (PKR)
  // ═══════════════════════════════════════════
  {
    code: 'nss_pk',
    asset: 'government_bonds',
    name: 'National Savings Pakistan',
    returnRate: 13,
    volatility: 2,
    minAmount: 10000,
    currency: 'PKR',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['PK'],
    description: 'Pakistan national savings certificates',
  },
  {
    code: 'psx_pk',
    asset: 'local_stocks',
    name: 'PSX KSE-100',
    returnRate: 15,
    volatility: 25,
    minAmount: 5000,
    currency: 'PKR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 5,
    availableIn: ['PK'],
    description: 'Pakistan Stock Exchange KSE-100 index',
  },

  // ═══════════════════════════════════════════
  // BANGLADESH (BDT)
  // ═══════════════════════════════════════════
  {
    code: 'fdr_bd',
    asset: 'term_deposit',
    name: 'FDR Bangladesh',
    returnRate: 7,
    volatility: 0,
    minAmount: 10000,
    currency: 'BDT',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['BD'],
    description: 'Bangladesh fixed deposit receipt',
  },
  {
    code: 'dse_bd',
    asset: 'local_stocks',
    name: 'DSE Broad Index',
    returnRate: 8,
    volatility: 22,
    minAmount: 5000,
    currency: 'BDT',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['BD'],
    description: 'Dhaka Stock Exchange broad index',
  },

  // ═══════════════════════════════════════════
  // SRI LANKA (LKR) + NÉPAL (NPR)
  // ═══════════════════════════════════════════
  {
    code: 'tbills_lk',
    asset: 'government_bonds',
    name: 'Sri Lanka T-Bills',
    returnRate: 10,
    volatility: 4,
    minAmount: 10000,
    currency: 'LKR',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['LK'],
    description: 'Sri Lanka government treasury bills',
  },
  {
    code: 'fd_np',
    asset: 'term_deposit',
    name: 'Nepal Fixed Deposit',
    returnRate: 8,
    volatility: 0,
    minAmount: 5000,
    currency: 'NPR',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['NP'],
    description: 'Nepal bank fixed deposit',
  },

  // ═══════════════════════════════════════════
  // ASIE DU SUD-EST
  // ═══════════════════════════════════════════
  {
    code: 'epf_my',
    asset: 'mutual_fund',
    name: 'EPF Malaysia',
    returnRate: 5.5,
    volatility: 3,
    minAmount: 0,
    currency: 'MYR',
    liquidity: 'locked',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'EPF',
    riskLevel: 1,
    availableIn: ['MY'],
    description: 'Employees Provident Fund, sharia-compliant option',
  },
  {
    code: 'asnb_my',
    asset: 'mutual_fund',
    name: 'ASNB Malaysia',
    returnRate: 5,
    volatility: 1,
    minAmount: 10,
    currency: 'MYR',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'Tax-exempt',
    riskLevel: 1,
    availableIn: ['MY'],
    description: 'Amanah Saham, government-backed unit trust',
  },
  {
    code: 'bursa_my',
    asset: 'local_stocks',
    name: 'Bursa KLCI',
    returnRate: 7,
    volatility: 14,
    minAmount: 500,
    currency: 'MYR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['MY'],
    description: 'Bursa Malaysia KLCI index',
  },
  {
    code: 'sbn_id',
    asset: 'government_bonds',
    name: 'SBN Indonesia',
    returnRate: 6.5,
    volatility: 2,
    minAmount: 1000000,
    currency: 'IDR',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['ID'],
    description: 'Indonesian retail government bonds',
  },
  {
    code: 'idx_id',
    asset: 'local_stocks',
    name: 'IDX Composite',
    returnRate: 9,
    volatility: 18,
    minAmount: 500000,
    currency: 'IDR',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['ID'],
    description: 'Indonesia Stock Exchange composite',
  },
  {
    code: 'ssf_th',
    asset: 'mutual_fund',
    name: 'SSF Thailand',
    returnRate: 7,
    volatility: 12,
    minAmount: 1000,
    currency: 'THB',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'SSF',
    riskLevel: 3,
    availableIn: ['TH'],
    description: 'Super Savings Fund, tax deduction up to 200,000 THB',
  },
  {
    code: 'set_th',
    asset: 'local_stocks',
    name: 'SET Index',
    returnRate: 8,
    volatility: 16,
    minAmount: 5000,
    currency: 'THB',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['TH'],
    description: 'Stock Exchange of Thailand index',
  },
  {
    code: 'uitf_ph',
    asset: 'mutual_fund',
    name: 'UITF Philippines',
    returnRate: 6,
    volatility: 10,
    minAmount: 5000,
    currency: 'PHP',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['PH'],
    description: 'Unit Investment Trust Fund, bank-managed',
  },
  {
    code: 'psei_ph',
    asset: 'local_stocks',
    name: 'PSEi Index',
    returnRate: 7,
    volatility: 18,
    minAmount: 5000,
    currency: 'PHP',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['PH'],
    description: 'Philippine Stock Exchange index',
  },
  {
    code: 'hose_vn',
    asset: 'local_stocks',
    name: 'VN-Index',
    returnRate: 10,
    volatility: 22,
    minAmount: 1000000,
    currency: 'VND',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['VN'],
    description: 'Ho Chi Minh Stock Exchange index',
  },
  {
    code: 'cpf_sg',
    asset: 'savings_account',
    name: 'CPF Singapore',
    returnRate: 4,
    volatility: 0,
    minAmount: 0,
    currency: 'SGD',
    liquidity: 'locked',
    shariaCompliant: true,
    taxAdvantaged: true,
    taxAdvantageName: 'CPF',
    riskLevel: 1,
    availableIn: ['SG'],
    description: 'Central Provident Fund, government-guaranteed',
  },
  {
    code: 'sti_sg',
    asset: 'local_stocks',
    name: 'STI Index',
    returnRate: 7,
    volatility: 12,
    minAmount: 100,
    currency: 'SGD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['SG'],
    description: 'Straits Times Index, Singapore top 30',
  },

  // ═══════════════════════════════════════════
  // ASIE DE L'EST
  // ═══════════════════════════════════════════
  {
    code: 'nisa_jp',
    asset: 'stock_index',
    name: 'NISA Japan',
    returnRate: 7,
    volatility: 14,
    minAmount: 1000,
    currency: 'JPY',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'NISA',
    riskLevel: 3,
    availableIn: ['JP'],
    description: 'Nippon ISA, tax-free investment account',
  },
  {
    code: 'nikkei_jp',
    asset: 'local_stocks',
    name: 'Nikkei 225 ETF',
    returnRate: 8,
    volatility: 18,
    minAmount: 1000,
    currency: 'JPY',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['JP'],
    description: 'Japanese stock market index',
  },
  {
    code: 'isa_kr',
    asset: 'stock_index',
    name: 'ISA Korea',
    returnRate: 7,
    volatility: 16,
    minAmount: 100000,
    currency: 'KRW',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'ISA',
    riskLevel: 3,
    availableIn: ['KR'],
    description: 'Korean Individual Savings Account, tax benefits',
  },
  {
    code: 'kospi_kr',
    asset: 'local_stocks',
    name: 'KOSPI Index',
    returnRate: 8,
    volatility: 18,
    minAmount: 50000,
    currency: 'KRW',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['KR'],
    description: 'Korea Composite Stock Price Index',
  },
  {
    code: 'yuebao_cn',
    asset: 'money_market',
    name: "Yu'E Bao",
    returnRate: 2,
    volatility: 0.5,
    minAmount: 1,
    currency: 'CNY',
    liquidity: 'immediate',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['CN'],
    description: 'Alipay money market fund, instant liquidity',
  },
  {
    code: 'csi300_cn',
    asset: 'local_stocks',
    name: 'CSI 300 ETF',
    returnRate: 8,
    volatility: 20,
    minAmount: 100,
    currency: 'CNY',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['CN'],
    description: 'China A-shares top 300 companies',
  },
  {
    code: 'hsi_hk',
    asset: 'local_stocks',
    name: 'Hang Seng Index',
    returnRate: 7,
    volatility: 18,
    minAmount: 1000,
    currency: 'HKD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['HK'],
    description: 'Hong Kong Hang Seng Index ETF',
  },
  {
    code: 'mpf_hk',
    asset: 'mutual_fund',
    name: 'MPF Hong Kong',
    returnRate: 5,
    volatility: 10,
    minAmount: 0,
    currency: 'HKD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'MPF',
    riskLevel: 2,
    availableIn: ['HK'],
    description: 'Mandatory Provident Fund, employer-matched',
  },
  {
    code: 'twse_tw',
    asset: 'local_stocks',
    name: 'TAIEX Index',
    returnRate: 10,
    volatility: 18,
    minAmount: 5000,
    currency: 'TWD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['TW'],
    description: 'Taiwan Stock Exchange Capitalization Index',
  },

  // ═══════════════════════════════════════════
  // OCÉANIE
  // ═══════════════════════════════════════════
  {
    code: 'super_au',
    asset: 'mutual_fund',
    name: 'Superannuation',
    returnRate: 8,
    volatility: 10,
    minAmount: 0,
    currency: 'AUD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'Super',
    riskLevel: 2,
    availableIn: ['AU'],
    description: 'Australian retirement fund, 15% tax on contributions',
  },
  {
    code: 'asx200_au',
    asset: 'local_stocks',
    name: 'ASX 200 ETF',
    returnRate: 8,
    volatility: 14,
    minAmount: 50,
    currency: 'AUD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['AU'],
    description: 'Australian Securities Exchange top 200',
  },
  {
    code: 'hisa_au',
    asset: 'savings_account',
    name: 'HISA Australia',
    returnRate: 4.5,
    volatility: 0,
    minAmount: 1,
    currency: 'AUD',
    liquidity: 'immediate',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 1,
    availableIn: ['AU'],
    description: 'High-interest savings account, government-insured',
  },
  {
    code: 'kiwisaver_nz',
    asset: 'mutual_fund',
    name: 'KiwiSaver',
    returnRate: 7,
    volatility: 10,
    minAmount: 0,
    currency: 'NZD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: true,
    taxAdvantageName: 'KiwiSaver',
    riskLevel: 2,
    availableIn: ['NZ'],
    description: 'NZ retirement savings, government + employer contributions',
  },
  {
    code: 'nzx50_nz',
    asset: 'local_stocks',
    name: 'NZX 50 Index',
    returnRate: 7,
    volatility: 12,
    minAmount: 50,
    currency: 'NZD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['NZ'],
    description: 'New Zealand Exchange top 50',
  },

  // ═══════════════════════════════════════════
  // FINANCE ISLAMIQUE (cross-country)
  // ═══════════════════════════════════════════
  {
    code: 'sukuk_global',
    asset: 'sukuk',
    name: 'Sukuk (obligations islamiques)',
    returnRate: 5,
    volatility: 4,
    minAmount: 1000,
    currency: 'USD',
    liquidity: 'months',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: [...GCC, 'MY', 'ID', 'NG', 'MA', 'TN', 'PK', 'BD', ...UEMOA, 'KE', 'TZ', 'TR', 'GB'],
    description: 'Obligations conformes à la charia',
  },
  {
    code: 'sukuk_my',
    asset: 'sukuk',
    name: 'Malaysian Sukuk',
    returnRate: 4.5,
    volatility: 3,
    minAmount: 1000,
    currency: 'MYR',
    liquidity: 'months',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['MY', 'ID', 'SG'],
    description: 'Malaysian government sukuk, largest market globally',
  },

  // ═══════════════════════════════════════════
  // ACTIFS GLOBAUX
  // ═══════════════════════════════════════════
  {
    code: 'gold_global',
    asset: 'gold',
    name: 'Or (ETF/physique)',
    returnRate: 5,
    volatility: 15,
    minAmount: 100,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: [...EUROZONE, 'CH', 'GB', 'US', 'CA', 'IN', ...GCC, 'PK', 'TR', 'AU', 'JP', 'KR', 'SG', 'ZA', 'MA', 'NG'],
    description: 'Valeur refuge, protection inflation',
  },
  {
    code: 'crypto_global',
    asset: 'crypto',
    name: 'Bitcoin / Stablecoins',
    returnRate: 15,
    volatility: 50,
    minAmount: 10,
    currency: 'USD',
    liquidity: 'immediate',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 5,
    availableIn: ['US', 'CA', 'GB', ...EUROZONE, 'CH', 'AU', 'NZ', 'SG', 'JP', 'KR', 'AE', 'NG', 'KE', 'ZA', 'BR', 'MX', 'IN', 'TR'],
    description: 'Crypto-monnaies, très haute volatilité',
  },
  {
    code: 'micro_enterprise',
    asset: 'micro_enterprise',
    name: 'Micro-commerce',
    returnRate: 20,
    volatility: 30,
    minAmount: 5000,
    currency: 'XOF',
    liquidity: 'locked',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 5,
    availableIn: [...UEMOA, ...CEMAC, 'GN', 'CD', 'HT', 'ET', ...EAST_AFRICA, 'NG', 'GH'],
    description: 'Petit commerce ou activité génératrice de revenus',
  },
  {
    code: 'etf_emerging',
    asset: 'stock_index',
    name: 'ETF Emerging Markets',
    returnRate: 8,
    volatility: 18,
    minAmount: 50,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: ['US', 'CA', 'GB', ...EUROZONE, 'CH', 'AU', 'NZ', 'SG', 'JP', 'HK'],
    description: 'Emerging markets index, diversification globale',
  },
  {
    code: 'corporate_bonds_global',
    asset: 'corporate_bonds',
    name: 'Corporate Bonds ETF',
    returnRate: 5,
    volatility: 6,
    minAmount: 100,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['US', 'CA', 'GB', ...EUROZONE, 'CH', 'AU', 'NZ', 'SG', 'JP'],
    description: 'Investment-grade corporate bonds diversifiées',
  },

  // ═══════════════════════════════════════════
  // PRIVATE EQUITY — Africa-focused
  // ═══════════════════════════════════════════
  {
    code: 'afig_fund_pe',
    asset: 'private_equity',
    name: 'AFIG Fund',
    returnRate: 15,
    volatility: 22,
    minAmount: 5000000,
    currency: 'XOF',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: UEMOA,
    description: 'Fonds de private equity Afrique de l\'Ouest',
  },
  {
    code: 'helios_pe',
    asset: 'private_equity',
    name: 'Helios Investment Partners',
    returnRate: 18,
    volatility: 25,
    minAmount: 50000,
    currency: 'USD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN],
    description: 'Pan-African private equity, multi-sector',
  },
  {
    code: 'dpi_africa_pe',
    asset: 'private_equity',
    name: 'DPI Africa Fund',
    returnRate: 16,
    volatility: 23,
    minAmount: 25000,
    currency: 'USD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN],
    description: 'Development Partners International, Pan-Africa growth equity',
  },
  {
    code: 'actis_energy_pe',
    asset: 'private_equity',
    name: 'Actis Energy',
    returnRate: 14,
    volatility: 20,
    minAmount: 100000,
    currency: 'USD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN],
    description: 'Pan-African energy infrastructure private equity',
  },

  // ═══════════════════════════════════════════
  // VENTURE CAPITAL — Africa-focused
  // ═══════════════════════════════════════════
  {
    code: 'partech_africa_vc',
    asset: 'venture_capital',
    name: 'Partech Africa',
    returnRate: 25,
    volatility: 40,
    minAmount: 10000,
    currency: 'USD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 5,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN, ...MAGHREB],
    description: 'Pan-African tech venture capital',
  },
  {
    code: 'tlcom_vc',
    asset: 'venture_capital',
    name: 'TLcom Capital',
    returnRate: 20,
    volatility: 35,
    minAmount: 25000,
    currency: 'USD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 5,
    availableIn: [...EAST_AFRICA, 'NG', 'GH'],
    description: 'East Africa & Nigeria tech venture capital',
  },
  {
    code: 'novastar_vc',
    asset: 'venture_capital',
    name: 'Novastar Ventures',
    returnRate: 22,
    volatility: 38,
    minAmount: 15000,
    currency: 'USD',
    liquidity: 'locked',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 5,
    availableIn: [...EAST_AFRICA, ...UEMOA, 'NG', 'GH'],
    description: 'East & West Africa early-stage venture capital',
  },

  // ═══════════════════════════════════════════
  // INFRASTRUCTURE — Africa-focused
  // ═══════════════════════════════════════════
  {
    code: 'africa50_infra',
    asset: 'infrastructure',
    name: 'Africa50 Infrastructure',
    returnRate: 8,
    volatility: 10,
    minAmount: 10000,
    currency: 'USD',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN, ...MAGHREB],
    description: 'Pan-African infrastructure development fund',
  },
  {
    code: 'meridiam_africa_infra',
    asset: 'infrastructure',
    name: 'Meridiam Africa',
    returnRate: 7,
    volatility: 9,
    minAmount: 25000,
    currency: 'EUR',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: [...UEMOA, ...CEMAC],
    description: 'West & Central Africa long-term infrastructure',
  },
  {
    code: 'lhgp_infra',
    asset: 'infrastructure',
    name: 'LHGP Infrastructure',
    returnRate: 9,
    volatility: 12,
    minAmount: 50000,
    currency: 'ZAR',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: SOUTHERN_AFRICA,
    description: 'Southern Africa infrastructure investment',
  },

  // ═══════════════════════════════════════════
  // ESG BONDS — Africa & Development Finance
  // ═══════════════════════════════════════════
  {
    code: 'afdb_green_bond',
    asset: 'esg_bonds',
    name: 'AfDB Green Bond',
    returnRate: 4.5,
    volatility: 5,
    minAmount: 1000,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: true,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN, ...MAGHREB],
    description: 'Obligation verte de la Banque Africaine de Developpement',
  },
  {
    code: 'ifc_social_bond',
    asset: 'esg_bonds',
    name: 'IFC Social Bond',
    returnRate: 4,
    volatility: 4.5,
    minAmount: 1000,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN, ...MAGHREB],
    description: 'IFC social impact bond, development finance',
  },
  {
    code: 'kenya_green_bond',
    asset: 'esg_bonds',
    name: 'Kenya Green Bond',
    returnRate: 5,
    volatility: 6,
    minAmount: 100000,
    currency: 'KES',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: ['KE'],
    description: 'Kenya green bond, sustainable infrastructure financing',
  },

  // ═══════════════════════════════════════════
  // AGROBUSINESS — Africa-focused
  // ═══════════════════════════════════════════
  {
    code: 'brvm_agri',
    asset: 'agrobusiness',
    name: 'BRVM Agri-Business',
    returnRate: 10,
    volatility: 18,
    minAmount: 100000,
    currency: 'XOF',
    liquidity: 'weeks',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: UEMOA,
    description: 'Actions agro-industrielles cotees BRVM',
  },
  {
    code: 'olam_agri',
    asset: 'agrobusiness',
    name: 'Olam Group',
    returnRate: 8,
    volatility: 15,
    minAmount: 5000,
    currency: 'USD',
    liquidity: 'weeks',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN],
    description: 'Pan-African agribusiness conglomerate',
  },
  {
    code: 'etg_agri',
    asset: 'agrobusiness',
    name: 'ETG',
    returnRate: 9,
    volatility: 16,
    minAmount: 10000,
    currency: 'USD',
    liquidity: 'weeks',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: [...EAST_AFRICA, ...SOUTHERN_AFRICA],
    description: 'East & Southern Africa agricultural trading group',
  },

  // ═══════════════════════════════════════════
  // MUNICIPAL BONDS — Africa regional
  // ═══════════════════════════════════════════
  {
    code: 'muni_cemac',
    asset: 'municipal_bonds',
    name: 'Obligations Communales CEMAC',
    returnRate: 4.5,
    volatility: 5,
    minAmount: 500000,
    currency: 'XAF',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: CEMAC,
    description: 'Obligations des collectivites locales CEMAC',
  },
  {
    code: 'muni_uemoa',
    asset: 'municipal_bonds',
    name: 'Muni Bond UEMOA',
    returnRate: 4,
    volatility: 4.5,
    minAmount: 500000,
    currency: 'XOF',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 2,
    availableIn: UEMOA,
    description: 'Obligations municipales UEMOA',
  },

  // ═══════════════════════════════════════════
  // MINING ASSETS — Africa-focused
  // ═══════════════════════════════════════════
  {
    code: 'randgold_mining',
    asset: 'mining_assets',
    name: 'Randgold Resources',
    returnRate: 12,
    volatility: 28,
    minAmount: 5000,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: [...SOUTHERN_AFRICA, ...UEMOA, ...CEMAC],
    description: 'Southern Africa gold mining equities',
  },
  {
    code: 'anglogold_mining',
    asset: 'mining_assets',
    name: 'AngloGold Ashanti',
    returnRate: 11,
    volatility: 25,
    minAmount: 3000,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: [...SOUTHERN_AFRICA, ...WEST_AFRICA_EN, ...EAST_AFRICA],
    description: 'Pan-African gold mining company',
  },

  // ═══════════════════════════════════════════
  // COMMODITIES — Global & Africa
  // ═══════════════════════════════════════════
  {
    code: 'ishares_gsci',
    asset: 'commodities',
    name: 'iShares GSCI Commodity',
    returnRate: 6,
    volatility: 18,
    minAmount: 500,
    currency: 'USD',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: ['US', 'CA', 'GB', ...EUROZONE, 'CH', 'AU', 'NZ', 'SG', 'JP', 'ZA'],
    description: 'Global commodity index ETF, diversified basket',
  },
  {
    code: 'cacao_brvm',
    asset: 'commodities',
    name: 'Cacao Futures BRVM',
    returnRate: 8,
    volatility: 22,
    minAmount: 200000,
    currency: 'XOF',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: UEMOA,
    description: 'Contrats a terme cacao, BRVM',
  },

  // ═══════════════════════════════════════════
  // VENTURE DEBT — Africa-focused
  // ═══════════════════════════════════════════
  {
    code: 'lendable_vd',
    asset: 'venture_debt',
    name: 'Lendable',
    returnRate: 12,
    volatility: 14,
    minAmount: 10000,
    currency: 'USD',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: EAST_AFRICA,
    description: 'East Africa fintech venture debt',
  },
  {
    code: 'vantage_vd',
    asset: 'venture_debt',
    name: 'Vantage Capital Mezzanine',
    returnRate: 14,
    volatility: 16,
    minAmount: 100000,
    currency: 'ZAR',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: SOUTHERN_AFRICA,
    description: 'Southern Africa growth-stage venture debt',
  },

  // ═══════════════════════════════════════════
  // CARBON CREDITS — Africa & Global
  // ═══════════════════════════════════════════
  {
    code: 'gold_standard_carbon',
    asset: 'carbon_credits',
    name: 'Gold Standard Carbon',
    returnRate: 8,
    volatility: 20,
    minAmount: 5000,
    currency: 'USD',
    liquidity: 'weeks',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN],
    description: 'Pan-African certified carbon offset credits',
  },
  {
    code: 'verra_vcs_carbon',
    asset: 'carbon_credits',
    name: 'Verra VCS Credits',
    returnRate: 7,
    volatility: 18,
    minAmount: 3000,
    currency: 'USD',
    liquidity: 'weeks',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 3,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN],
    description: 'Verified Carbon Standard credits, Pan-Africa',
  },

  // ═══════════════════════════════════════════
  // TOKENIZED ASSETS — Digital Finance Africa
  // ═══════════════════════════════════════════
  {
    code: 'afritoken_re',
    asset: 'tokenized_assets',
    name: 'AfriToken Real Estate',
    returnRate: 10,
    volatility: 22,
    minAmount: 100,
    currency: 'USDT',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: [...UEMOA, ...CEMAC, ...EAST_AFRICA, ...SOUTHERN_AFRICA, ...WEST_AFRICA_EN],
    description: 'Tokenized Pan-African real estate fractions',
  },
  {
    code: 'bitpesa_tf',
    asset: 'tokenized_assets',
    name: 'BitPesa Trade Finance',
    returnRate: 12,
    volatility: 25,
    minAmount: 200,
    currency: 'USDT',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: [...EAST_AFRICA, ...WEST_AFRICA_EN, ...UEMOA],
    description: 'Tokenized trade finance, East & West Africa',
  },

  // ═══════════════════════════════════════════
  // MEZZANINE — Africa-focused
  // ═══════════════════════════════════════════
  {
    code: 'vantage_mezzanine',
    asset: 'mezzanine',
    name: 'Vantage Capital Mezzanine Fund',
    returnRate: 13,
    volatility: 15,
    minAmount: 200000,
    currency: 'ZAR',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: SOUTHERN_AFRICA,
    description: 'Southern Africa mezzanine growth finance',
  },
  {
    code: 'norsad_mezzanine',
    asset: 'mezzanine',
    name: 'Norsad Capital',
    returnRate: 11,
    volatility: 14,
    minAmount: 50000,
    currency: 'USD',
    liquidity: 'months',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 4,
    availableIn: [...SOUTHERN_AFRICA, ...EAST_AFRICA],
    description: 'Southern & East Africa mezzanine debt fund',
  },

  // ═══════════════════════════════════════════
  // DERIVATIVES — Africa regional
  // ═══════════════════════════════════════════
  {
    code: 'brvm_options',
    asset: 'derivatives',
    name: 'BRVM Options Index',
    returnRate: 15,
    volatility: 45,
    minAmount: 1000000,
    currency: 'XOF',
    liquidity: 'days',
    shariaCompliant: false,
    taxAdvantaged: false,
    riskLevel: 5,
    availableIn: UEMOA,
    description: 'Options sur indice BRVM, haute volatilite',
  },
];

/**
 * Filter products available for a given country code.
 */
export function getProductsForCountry(countryCode: string): InvestmentProduct[] {
  const cc = countryCode.toUpperCase();
  return INVESTMENT_PRODUCTS.filter((p) => p.availableIn.includes(cc));
}

/**
 * Filter products by sharia compliance.
 */
export function filterShariaProducts(
  products: InvestmentProduct[],
  compliance: 'required' | 'preferred' | 'not_required',
): InvestmentProduct[] {
  if (compliance === 'not_required') return products;
  if (compliance === 'required') return products.filter((p) => p.shariaCompliant);
  // preferred: sort sharia-compliant first but include all
  return [...products].sort((a, b) => (b.shariaCompliant ? 1 : 0) - (a.shariaCompliant ? 1 : 0));
}

/**
 * Get all unique country codes covered by the catalogue.
 */
export function getCoveredCountries(): string[] {
  const countries = new Set<string>();
  for (const p of INVESTMENT_PRODUCTS) {
    for (const cc of p.availableIn) {
      countries.add(cc);
    }
  }
  return Array.from(countries).sort();
}
